//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contribuyente.Impuestos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NitField;
        
        private int ciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private int numeroFacturaField;
        
        private int CUFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contribuyente.Impuestos.TipoDocumentoCliente tipoDocumentoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contribuyente.Impuestos.ArrayOfString listaDetalleFacturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Nit {
            get {
                return this.NitField;
            }
            set {
                if ((this.NitField.Equals(value) != true)) {
                    this.NitField = value;
                    this.RaisePropertyChanged("Nit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ci {
            get {
                return this.ciField;
            }
            set {
                if ((this.ciField.Equals(value) != true)) {
                    this.ciField = value;
                    this.RaisePropertyChanged("ci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razonSocialField, value) != true)) {
                    this.razonSocialField = value;
                    this.RaisePropertyChanged("razonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int numeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                if ((this.numeroFacturaField.Equals(value) != true)) {
                    this.numeroFacturaField = value;
                    this.RaisePropertyChanged("numeroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CUF {
            get {
                return this.CUFField;
            }
            set {
                if ((this.CUFField.Equals(value) != true)) {
                    this.CUFField = value;
                    this.RaisePropertyChanged("CUF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Contribuyente.Impuestos.TipoDocumentoCliente tipoDocumentoCliente {
            get {
                return this.tipoDocumentoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoDocumentoClienteField, value) != true)) {
                    this.tipoDocumentoClienteField = value;
                    this.RaisePropertyChanged("tipoDocumentoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreClienteField, value) != true)) {
                    this.nombreClienteField = value;
                    this.RaisePropertyChanged("nombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Contribuyente.Impuestos.ArrayOfString listaDetalleFactura {
            get {
                return this.listaDetalleFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.listaDetalleFacturaField, value) != true)) {
                    this.listaDetalleFacturaField = value;
                    this.RaisePropertyChanged("listaDetalleFactura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumentoCliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TipoDocumentoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NITField;
        
        private int CIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NIT {
            get {
                return this.NITField;
            }
            set {
                if ((this.NITField.Equals(value) != true)) {
                    this.NITField = value;
                    this.RaisePropertyChanged("NIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CI {
            get {
                return this.CIField;
            }
            set {
                if ((this.CIField.Equals(value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Impuestos.ImpuestosSoap")]
    public interface ImpuestosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sincronizarFechaHoraResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sincronizarFechaHora", ReplyAction="*")]
        Contribuyente.Impuestos.sincronizarFechaHoraResponse sincronizarFechaHora(Contribuyente.Impuestos.sincronizarFechaHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sincronizarFechaHora", ReplyAction="*")]
        System.Threading.Tasks.Task<Contribuyente.Impuestos.sincronizarFechaHoraResponse> sincronizarFechaHoraAsync(Contribuyente.Impuestos.sincronizarFechaHoraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idambiente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCufd", ReplyAction="*")]
        Contribuyente.Impuestos.obtenerCufdResponse obtenerCufd(Contribuyente.Impuestos.obtenerCufdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCufd", ReplyAction="*")]
        System.Threading.Tasks.Task<Contribuyente.Impuestos.obtenerCufdResponse> obtenerCufdAsync(Contribuyente.Impuestos.obtenerCufdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cufd del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirFactura", ReplyAction="*")]
        Contribuyente.Impuestos.EmitirFacturaResponse EmitirFactura(Contribuyente.Impuestos.EmitirFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<Contribuyente.Impuestos.EmitirFacturaResponse> EmitirFacturaAsync(Contribuyente.Impuestos.EmitirFacturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sincronizarFechaHoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sincronizarFechaHora", Namespace="http://tempuri.org/", Order=0)]
        public Contribuyente.Impuestos.sincronizarFechaHoraRequestBody Body;
        
        public sincronizarFechaHoraRequest() {
        }
        
        public sincronizarFechaHoraRequest(Contribuyente.Impuestos.sincronizarFechaHoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sincronizarFechaHoraRequestBody {
        
        public sincronizarFechaHoraRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sincronizarFechaHoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sincronizarFechaHoraResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contribuyente.Impuestos.sincronizarFechaHoraResponseBody Body;
        
        public sincronizarFechaHoraResponse() {
        }
        
        public sincronizarFechaHoraResponse(Contribuyente.Impuestos.sincronizarFechaHoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sincronizarFechaHoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sincronizarFechaHoraResult;
        
        public sincronizarFechaHoraResponseBody() {
        }
        
        public sincronizarFechaHoraResponseBody(string sincronizarFechaHoraResult) {
            this.sincronizarFechaHoraResult = sincronizarFechaHoraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCufdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCufd", Namespace="http://tempuri.org/", Order=0)]
        public Contribuyente.Impuestos.obtenerCufdRequestBody Body;
        
        public obtenerCufdRequest() {
        }
        
        public obtenerCufdRequest(Contribuyente.Impuestos.obtenerCufdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCufdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idambiente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int modalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nit;
        
        public obtenerCufdRequestBody() {
        }
        
        public obtenerCufdRequestBody(string idambiente, int modalidad, int nit) {
            this.idambiente = idambiente;
            this.modalidad = modalidad;
            this.nit = nit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCufdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCufdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contribuyente.Impuestos.obtenerCufdResponseBody Body;
        
        public obtenerCufdResponse() {
        }
        
        public obtenerCufdResponse(Contribuyente.Impuestos.obtenerCufdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCufdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerCufdResult;
        
        public obtenerCufdResponseBody() {
        }
        
        public obtenerCufdResponseBody(string obtenerCufdResult) {
            this.obtenerCufdResult = obtenerCufdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFactura", Namespace="http://tempuri.org/", Order=0)]
        public Contribuyente.Impuestos.EmitirFacturaRequestBody Body;
        
        public EmitirFacturaRequest() {
        }
        
        public EmitirFacturaRequest(Contribuyente.Impuestos.EmitirFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idambiente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Nitnumero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cufd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int modalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Contribuyente.Impuestos.Factura factura;
        
        public EmitirFacturaRequestBody() {
        }
        
        public EmitirFacturaRequestBody(int idambiente, int Nitnumero, string cufd, int modalidad, Contribuyente.Impuestos.Factura factura) {
            this.idambiente = idambiente;
            this.Nitnumero = Nitnumero;
            this.cufd = cufd;
            this.modalidad = modalidad;
            this.factura = factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contribuyente.Impuestos.EmitirFacturaResponseBody Body;
        
        public EmitirFacturaResponse() {
        }
        
        public EmitirFacturaResponse(Contribuyente.Impuestos.EmitirFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmitirFacturaResult;
        
        public EmitirFacturaResponseBody() {
        }
        
        public EmitirFacturaResponseBody(string EmitirFacturaResult) {
            this.EmitirFacturaResult = EmitirFacturaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImpuestosSoapChannel : Contribuyente.Impuestos.ImpuestosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImpuestosSoapClient : System.ServiceModel.ClientBase<Contribuyente.Impuestos.ImpuestosSoap>, Contribuyente.Impuestos.ImpuestosSoap {
        
        public ImpuestosSoapClient() {
        }
        
        public ImpuestosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImpuestosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImpuestosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImpuestosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contribuyente.Impuestos.sincronizarFechaHoraResponse Contribuyente.Impuestos.ImpuestosSoap.sincronizarFechaHora(Contribuyente.Impuestos.sincronizarFechaHoraRequest request) {
            return base.Channel.sincronizarFechaHora(request);
        }
        
        public string sincronizarFechaHora() {
            Contribuyente.Impuestos.sincronizarFechaHoraRequest inValue = new Contribuyente.Impuestos.sincronizarFechaHoraRequest();
            inValue.Body = new Contribuyente.Impuestos.sincronizarFechaHoraRequestBody();
            Contribuyente.Impuestos.sincronizarFechaHoraResponse retVal = ((Contribuyente.Impuestos.ImpuestosSoap)(this)).sincronizarFechaHora(inValue);
            return retVal.Body.sincronizarFechaHoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Contribuyente.Impuestos.sincronizarFechaHoraResponse> Contribuyente.Impuestos.ImpuestosSoap.sincronizarFechaHoraAsync(Contribuyente.Impuestos.sincronizarFechaHoraRequest request) {
            return base.Channel.sincronizarFechaHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<Contribuyente.Impuestos.sincronizarFechaHoraResponse> sincronizarFechaHoraAsync() {
            Contribuyente.Impuestos.sincronizarFechaHoraRequest inValue = new Contribuyente.Impuestos.sincronizarFechaHoraRequest();
            inValue.Body = new Contribuyente.Impuestos.sincronizarFechaHoraRequestBody();
            return ((Contribuyente.Impuestos.ImpuestosSoap)(this)).sincronizarFechaHoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contribuyente.Impuestos.obtenerCufdResponse Contribuyente.Impuestos.ImpuestosSoap.obtenerCufd(Contribuyente.Impuestos.obtenerCufdRequest request) {
            return base.Channel.obtenerCufd(request);
        }
        
        public string obtenerCufd(string idambiente, int modalidad, int nit) {
            Contribuyente.Impuestos.obtenerCufdRequest inValue = new Contribuyente.Impuestos.obtenerCufdRequest();
            inValue.Body = new Contribuyente.Impuestos.obtenerCufdRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.modalidad = modalidad;
            inValue.Body.nit = nit;
            Contribuyente.Impuestos.obtenerCufdResponse retVal = ((Contribuyente.Impuestos.ImpuestosSoap)(this)).obtenerCufd(inValue);
            return retVal.Body.obtenerCufdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Contribuyente.Impuestos.obtenerCufdResponse> Contribuyente.Impuestos.ImpuestosSoap.obtenerCufdAsync(Contribuyente.Impuestos.obtenerCufdRequest request) {
            return base.Channel.obtenerCufdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Contribuyente.Impuestos.obtenerCufdResponse> obtenerCufdAsync(string idambiente, int modalidad, int nit) {
            Contribuyente.Impuestos.obtenerCufdRequest inValue = new Contribuyente.Impuestos.obtenerCufdRequest();
            inValue.Body = new Contribuyente.Impuestos.obtenerCufdRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.modalidad = modalidad;
            inValue.Body.nit = nit;
            return ((Contribuyente.Impuestos.ImpuestosSoap)(this)).obtenerCufdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contribuyente.Impuestos.EmitirFacturaResponse Contribuyente.Impuestos.ImpuestosSoap.EmitirFactura(Contribuyente.Impuestos.EmitirFacturaRequest request) {
            return base.Channel.EmitirFactura(request);
        }
        
        public string EmitirFactura(int idambiente, int Nitnumero, string cufd, int modalidad, Contribuyente.Impuestos.Factura factura) {
            Contribuyente.Impuestos.EmitirFacturaRequest inValue = new Contribuyente.Impuestos.EmitirFacturaRequest();
            inValue.Body = new Contribuyente.Impuestos.EmitirFacturaRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.Nitnumero = Nitnumero;
            inValue.Body.cufd = cufd;
            inValue.Body.modalidad = modalidad;
            inValue.Body.factura = factura;
            Contribuyente.Impuestos.EmitirFacturaResponse retVal = ((Contribuyente.Impuestos.ImpuestosSoap)(this)).EmitirFactura(inValue);
            return retVal.Body.EmitirFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Contribuyente.Impuestos.EmitirFacturaResponse> Contribuyente.Impuestos.ImpuestosSoap.EmitirFacturaAsync(Contribuyente.Impuestos.EmitirFacturaRequest request) {
            return base.Channel.EmitirFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Contribuyente.Impuestos.EmitirFacturaResponse> EmitirFacturaAsync(int idambiente, int Nitnumero, string cufd, int modalidad, Contribuyente.Impuestos.Factura factura) {
            Contribuyente.Impuestos.EmitirFacturaRequest inValue = new Contribuyente.Impuestos.EmitirFacturaRequest();
            inValue.Body = new Contribuyente.Impuestos.EmitirFacturaRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.Nitnumero = Nitnumero;
            inValue.Body.cufd = cufd;
            inValue.Body.modalidad = modalidad;
            inValue.Body.factura = factura;
            return ((Contribuyente.Impuestos.ImpuestosSoap)(this)).EmitirFacturaAsync(inValue);
        }
    }
}
