//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contribuyente.Banco {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Banco.BancoSoap")]
    public interface BancoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento moneda del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obternerCotizacion", ReplyAction="*")]
        Contribuyente.Banco.obternerCotizacionResponse obternerCotizacion(Contribuyente.Banco.obternerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obternerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Contribuyente.Banco.obternerCotizacionResponse> obternerCotizacionAsync(Contribuyente.Banco.obternerCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obternerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obternerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public Contribuyente.Banco.obternerCotizacionRequestBody Body;
        
        public obternerCotizacionRequest() {
        }
        
        public obternerCotizacionRequest(Contribuyente.Banco.obternerCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obternerCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string moneda;
        
        public obternerCotizacionRequestBody() {
        }
        
        public obternerCotizacionRequestBody(string moneda) {
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obternerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obternerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Contribuyente.Banco.obternerCotizacionResponseBody Body;
        
        public obternerCotizacionResponse() {
        }
        
        public obternerCotizacionResponse(Contribuyente.Banco.obternerCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obternerCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double obternerCotizacionResult;
        
        public obternerCotizacionResponseBody() {
        }
        
        public obternerCotizacionResponseBody(double obternerCotizacionResult) {
            this.obternerCotizacionResult = obternerCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BancoSoapChannel : Contribuyente.Banco.BancoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BancoSoapClient : System.ServiceModel.ClientBase<Contribuyente.Banco.BancoSoap>, Contribuyente.Banco.BancoSoap {
        
        public BancoSoapClient() {
        }
        
        public BancoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BancoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Contribuyente.Banco.obternerCotizacionResponse Contribuyente.Banco.BancoSoap.obternerCotizacion(Contribuyente.Banco.obternerCotizacionRequest request) {
            return base.Channel.obternerCotizacion(request);
        }
        
        public double obternerCotizacion(string moneda) {
            Contribuyente.Banco.obternerCotizacionRequest inValue = new Contribuyente.Banco.obternerCotizacionRequest();
            inValue.Body = new Contribuyente.Banco.obternerCotizacionRequestBody();
            inValue.Body.moneda = moneda;
            Contribuyente.Banco.obternerCotizacionResponse retVal = ((Contribuyente.Banco.BancoSoap)(this)).obternerCotizacion(inValue);
            return retVal.Body.obternerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Contribuyente.Banco.obternerCotizacionResponse> Contribuyente.Banco.BancoSoap.obternerCotizacionAsync(Contribuyente.Banco.obternerCotizacionRequest request) {
            return base.Channel.obternerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Contribuyente.Banco.obternerCotizacionResponse> obternerCotizacionAsync(string moneda) {
            Contribuyente.Banco.obternerCotizacionRequest inValue = new Contribuyente.Banco.obternerCotizacionRequest();
            inValue.Body = new Contribuyente.Banco.obternerCotizacionRequestBody();
            inValue.Body.moneda = moneda;
            return ((Contribuyente.Banco.BancoSoap)(this)).obternerCotizacionAsync(inValue);
        }
    }
}
