//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.BancoBNB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BancoBNB.BancoBNBSoap")]
    public interface BancoBNBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaSaldo", ReplyAction="*")]
        double ConsultaSaldo(int rocuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ConsultaSaldoAsync(int rocuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BancoBNBSoapChannel : Cliente.BancoBNB.BancoBNBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BancoBNBSoapClient : System.ServiceModel.ClientBase<Cliente.BancoBNB.BancoBNBSoap>, Cliente.BancoBNB.BancoBNBSoap {
        
        public BancoBNBSoapClient() {
        }
        
        public BancoBNBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BancoBNBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoBNBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoBNBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ConsultaSaldo(int rocuenta) {
            return base.Channel.ConsultaSaldo(rocuenta);
        }
        
        public System.Threading.Tasks.Task<double> ConsultaSaldoAsync(int rocuenta) {
            return base.Channel.ConsultaSaldoAsync(rocuenta);
        }
    }
}
